Add release note and update versions to v2.3
microsoft/nni pull request #3738
Opened 2021-06-08 13:54 UTC by kvartet

remember to update the release date :)

Documentation update needed:

+ Retiarii doc
+ 3rd-party training service doc
+ setting prefix URL doc
+ Tensorflow slim pruner doc

2021-06-09 03:39 UTC, scarlett2018 requested changes

2021-06-09 03:39 UTC, scarlett2018 commented on docs/en_US/Release.rst
> +* Remove tensorboard code on nnictl (#3613)
add an explanation about why we remove it?

2021-06-09 03:39 UTC, scarlett2018 commented on docs/en_US/Release.rst
> +* Add pipeline badge in README (#3589)
this is not document or example, but developer/code health management. can move it to others.

2021-06-09 03:39 UTC, scarlett2018 commented on docs/en_US/Release.rst
> +""""""
Others --> DEV excellent

2021-06-09 03:40 UTC, scarlett2018 commented
I had also made a quick fix on the retiarii part and merged to the PR directly.

2021-06-09 06:58 UTC, scarlett2018 reviewed
update link

2021-06-10 04:00 UTC, kvartet commented
@scarlett2018 updated all.

2021-06-10 07:34 UTC, ultmaster commented on docs/en_US/Release.rst
> +Dev Excellent
What is Dev Excellent

2021-06-10 07:41 UTC, ultmaster approved these changes

2021-06-15 05:02 UTC, scarlett2018 commented on README.md
> +* **New release**: [v2.3 is available](https://github.com/microsoft/nni/releases) - _released on April-26-2021_
>_released on April-26-2021

6/15/2021

2021-06-15 05:03 UTC, J-shang approved these changes

2021-06-15 06:10 UTC, scarlett2018 approved these changes

2021-06-15 07:07 UTC, QuanluZhang approved these changes

2021-06-15 08:24 UTC, SparkSnail approved these changes

2021-06-15 10:09 UTC, liuzhe-lz approved these changes

2021-06-15 10:19 UTC, merged